require: rubocop-rspec

inherit_from: .rubocop_todo.yml

AllCops:
  DisplayStyleGuide: true
  Exclude:
    - 'bin/bundle'
    - 'bin/puma'
    - 'bin/rspec'
    - 'bin/sidekiq'
    - 'bin/rubocop'

Rails:
  Enabled: true

# because project using mongoid
Rails/HasAndBelongsToMany:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'config/routes.rb'
