AllCops:
  DisplayStyleGuide: true

Rails:
  Enabled: true

# because project using mongoid
Rails/HasAndBelongsToMany:
  Enabled: false

Style/Documentation:
  Enabled: false

# Offense count: 2
Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'
