AllCops:
  DisplayStyleGuide: true
  Exclude:
    - 'bin/bundle'
    - 'bin/puma'
    - 'bin/rspec'

Rails:
  Enabled: true

# because project using mongoid
Rails/HasAndBelongsToMany:
  Enabled: false

Style/Documentation:
  Enabled: false

# Offense count: 2
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 11
